### ISSUE TITLE
Smaller feed?

### ISSUE THREAD

**Issue by fletom** [kaini/hnbest#5]
Would it be difficult to add a feature to show less items in the feed? Maybe sorting items by points and only displaying the top half? So there would be multiple URLs depending on how much HN you actually want to read. I'm subbed to the RSS feed and the number of items can get overwhelming.

I'd take a crack at it myself but my Ruby isn't good enough and I'd probably do it wrong.

**Comment by kaini** [comment]
Thats no problem, I can implement a GET parameter that limits the number of entries in the RSS feed (currently it is 30, because hn/best displays 30 items as well), ordered by the *current* amount of points, the news item has.

The RSS item will always show the number of points the news item had, when it was first seen, because I don't think it's a good idea to change an already published RSS entry.

**Comment by fletom** [comment]
Sounds great!

**Comment by kaini** [comment]
It's done! For example: http://hnbest.herokuapp.com/rss?count=15

**Comment by fletom** [comment]
Thanks so much. :)

**Comment by fletom** [comment]
Hey, I'm testing http://hnbest.herokuapp.com/rss?count=10 but it doesn't seem to be updating properly.

These are the current top ten items by points on /best.
![screen shot 2015-02-20 at 12 50 23 am](https://cloud.githubusercontent.com/assets/127497/6281980/908f92e6-b89a-11e4-9f64-62dbca35233c.png)


Here is the feed hnbest is currently outputting: https://gist.github.com/fletom/09ce5e3688b98318b331

There are only 4 items in common and they seem to be the older submissions ("Fuck It, I'm Going Back to Firefox", "Ask HN: The “I want to do everything but end up doing nothing” dilemma", "Now, I can see wifi signals", "Stop Using LinkedIn").

Any ideas?

**Comment by kaini** [comment]
Fixed.
I made an error in the SQL statement fetching the feed items. (Sequel did not nest the query the way I anticipated it.)

**Comment by fletom** [comment]
Great, it works now, thanks again!
