### ISSUE TITLE
Down?

### ISSUE THREAD

**Issue by piec** [kaini/hnbest#7]
Hi,

I suppose the project is down due to the end of heroku free plan?
Thanks for the rss I've used for all these years anyway 🙂

Cheers,
Pierre

**Comment by maurice-schleussinger** [comment]
> Hi,
> 
> I suppose the project is down due to the end of heroku free plan? Thanks for the rss I've used for all these years anyway 🙂
> 
> Cheers, Pierre

Same here. I found this alternative: https://hnrss.org/best (documentation: https://hnrss.github.io)

But thank you @kaini for providing this in the first place!

**Comment by kaini** [comment]
Yes, you are right, this is the reason. Thanks for the kind words and I would recommend to just use the alternative proposed by Maurice.
